jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Sweepo\UserBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            security: false

        main:
            pattern:    ^/
            anonymous: true
            twitter:  ~

            form_login:
                login_path:  /

            logout:
                path: /logout
                target: /
                success_handler: sweepo.logout.handler
