<?php

namespace Sweepo\StreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Sweepo\UserBundle\Entity\User;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
}
