<?php

namespace Sweepo\StreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Sweepo\UserBundle\Entity\User;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    public function findByKeywords(User $user)
    {
        $qb = $this->createQueryBuilder('s');

        return $qb->select('s.subscription')
            ->where('s.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
