<?php

namespace Sweepo\StreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Sweepo\UserBundle\Entity\User;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    public function getLastId(User $user)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.tweet_id')
            ->where('t.user = :user')
            ->setParameter('user', $user)
            ->setMaxResults(1)
            ->orderBy('t.tweet_created_at', 'DESC')
            ->getQuery();

        try {
            $id = $qb->getSingleScalarResult();
        } catch (\Exception $e) {
            $id = null;
        }

        return $id;
    }

    /**
     * Get the stream
     * @param  User     $user User concerned
     * @param  DateTime $date Used in crontab task for daily email. We specified the date
     *                        to get all the tweet with a created date greater than today
     */
    public function getStream(User $user, $date = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.user = :user');

        if (null !== $date) {
            $qb->andWhere($qb->expr()->gte('t.tweet_created_at', '?1'))
                ->setParameter(1, $date);
        }

        return $qb->orderBy('t.tweet_created_at', 'DESC')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

    public function getTweetId(User $user)
    {
        return $this->createQueryBuilder('t')
            ->select('t.tweet_id')
            ->where('t.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
