<?php

namespace Sweepo\StreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Sweepo\UserBundle\Entity\User;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    public function getLastId(User $user)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.tweet_id')
            ->where('t.user = :user')
            ->setParameter('user', $user)
            ->setMaxResults(1)
            ->orderBy('t.tweet_created_at', 'DESC')
            ->getQuery();

        try {
            $id = $qb->getSingleScalarResult();
        } catch (\Exception $e) {
            $id = null;
        }

        return $id;
    }

    public function getStream(User $user, $sinceId = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.user = :user')
            ->setParameter('user', $user);

        if (null !== $sinceId) {
            $qb->andWhere('t.id > :sinceId')
                ->setParameter('sinceId', $sinceId);
        }

        return $qb->orderBy('t.tweet_created_at', 'DESC')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
